// Package journey — Regression test codification (S14). Given a ratified
// journeys artefact and a set of human-walkthrough attestations, codify each
// walked-pass journey as an automated regression test scaffold. The output is a
// Go test file per journey, structured but not functionally complete — the
// project adapts the scaffold into a real E2E test.
//
// The codification is accretive: previously-codified journeys are preserved,
// only walked-but-not-yet-codified journeys generate new scaffolds.
package journey

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RegressionCoverageGaps returns journey IDs that have a passing walkthrough
// attestation but no regression test coverage. These are "flagged for
// regression" with no committed test — the caller (sworn journeys --regen)
// should exit non-zero and name them.
//
// A journey has regression coverage when:
//   - HasRegression is true OR
//   - RegressionTestPath is non-empty AND the file exists on disk
//
// Only journeys with a WalkPass attestation are considered eligible for
// regression coverage.
func RegressionCoverageGaps(a *JourneyArtefact, attArtefact *AttestationArtefact, projectRoot string) []string {
	if a == nil || attArtefact == nil {
		return nil
	}

	// Build a lookup of passing attestations.
	passed := make(map[string]bool)
	for _, att := range attArtefact.Attestations {
		if att.Status == WalkPass {
			passed[att.JourneyID] = true
		}
	}

	var gaps []string
	for _, j := range a.Journeys {
		if !passed[j.ID] {
			continue // not eligible — no passing walkthrough
		}

		// Check existing coverage.
		covered := j.HasRegression
		if !covered && j.RegressionTestPath != "" {
			if _, err := os.Stat(filepath.Join(projectRoot, j.RegressionTestPath)); err == nil {
				covered = true
			}
		}

		if !covered {
			gaps = append(gaps, j.ID)
		}
	}

	sort.Strings(gaps)
	return gaps
}

// CodifyJourney generates a regression test scaffold for a single journey and
// returns the path to the generated file (relative to projectRoot). The
// scaffold is a Go test file with structured steps as comments and a skip
// marker. It does NOT overwrite an existing file — the caller should check
// HasRegression or file existence first.
//
// outputDir is the directory under projectRoot where the scaffold is written
// (e.g. "tests/e2e/journeys"). The file name is derived from the journey ID:
// "journey_<id>_test.go" (non-alphanumeric characters replaced with underscores).
func CodifyJourney(j *Journey, outputDir, projectRoot string) (string, error) {
	if outputDir == "" {
		outputDir = "tests/e2e/journeys"
	}

	// Build a file-safe name from the journey ID.
	fileName := fmt.Sprintf("journey_%s_test.go", sanitiseID(j.ID))
	relPath := filepath.Join(outputDir, fileName)
	absPath := filepath.Join(projectRoot, relPath)

	// Check that the output directory exists; create if needed.
	absDir := filepath.Dir(absPath)
	if err := os.MkdirAll(absDir, 0755); err != nil {
		return "", fmt.Errorf("codify: mkdir %s: %w", absDir, err)
	}

	// Check if file already exists — accretive, do not overwrite.
	if _, err := os.Stat(absPath); err == nil {
		return "", fmt.Errorf("codify: scaffold already exists at %s (accretive — will not overwrite)", relPath)
	}

	content := buildScaffold(j, relPath)

	if err := os.WriteFile(absPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("codify: write %s: %w", absPath, err)
	}

	return relPath, nil
}

// buildScaffold generates the Go test file content for a journey scaffold.
func buildScaffold(j *Journey, relPath string) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Code generated by sworn journeys --regen. DO NOT EDIT.\n"))
	b.WriteString(fmt.Sprintf("//\n"))
	b.WriteString(fmt.Sprintf("// Journey: %s\n", j.ID))
	b.WriteString(fmt.Sprintf("// User:    %s\n", j.UserType))
	b.WriteString(fmt.Sprintf("// Outcome: %s\n", j.Outcome))
	b.WriteString(fmt.Sprintf("// Entry:   %s\n", j.EntrySurface))
	b.WriteString(fmt.Sprintf("//\n"))
	b.WriteString(fmt.Sprintf("// Source: %s\n", relPath))
	b.WriteString(fmt.Sprintf("\n"))
	b.WriteString(fmt.Sprintf("package journey_test\n"))
	b.WriteString(fmt.Sprintf("\n"))
	b.WriteString(fmt.Sprintf("import \"testing\"\n"))
	b.WriteString(fmt.Sprintf("\n"))

	// Generate the test function name from the journey ID.
	funcName := fmt.Sprintf("TestJourney_%s", sanitiseID(j.ID))
	b.WriteString(fmt.Sprintf("// %s tests journey %q.\n", funcName, j.ID))
	b.WriteString(fmt.Sprintf("//\n"))
	if j.EntrySurface != "" {
		b.WriteString(fmt.Sprintf("// Entry surface: %s\n", j.EntrySurface))
	}
	if len(j.Steps) > 0 {
		b.WriteString(fmt.Sprintf("//\n"))
		b.WriteString(fmt.Sprintf("// Steps:\n"))
		for _, step := range j.Steps {
			b.WriteString(fmt.Sprintf("//   %d. %s", step.Order, step.Description))
			if step.Surface != "" {
				b.WriteString(fmt.Sprintf(" (%s)", step.Surface))
			}
			b.WriteString(fmt.Sprintf("\n"))
		}
	}
	b.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", funcName))

	if len(j.Steps) > 0 {
		b.WriteString(fmt.Sprintf("\t//\n"))
		b.WriteString(fmt.Sprintf("\t// Journey steps to assert:\n"))
		for _, step := range j.Steps {
			b.WriteString(fmt.Sprintf("\t//   %d. %s", step.Order, step.Description))
			if step.Surface != "" {
				b.WriteString(fmt.Sprintf(" (%s)", step.Surface))
			}
			b.WriteString(fmt.Sprintf("\n"))
		}
	}

	b.WriteString(fmt.Sprintf("\tt.Skip(\"Regression scaffold — implement steps above\")\n"))
	b.WriteString(fmt.Sprintf("}\n"))

	return b.String()
}

// sanitiseID replaces non-alphanumeric characters with underscores for use in
// Go function and file names. It lowercases the result.
func sanitiseID(id string) string {
	var b strings.Builder
	for _, r := range id {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return strings.ToLower(b.String())
}

// CodifyWalkedJourneys codifies every walked-pass journey that does not yet
// have regression coverage. It returns the list of generated file paths and
// updates the artefact's Journey entries with HasRegression and
// RegressionTestPath. The caller is responsible for saving the artefact.
//
// outputDir is relative to projectRoot (default "tests/e2e/journeys").
func CodifyWalkedJourneys(a *JourneyArtefact, attArtefact *AttestationArtefact, outputDir, projectRoot string) ([]string, error) {
	if a == nil {
		return nil, fmt.Errorf("codify: artefacts is nil")
	}
	if attArtefact == nil {
		return nil, fmt.Errorf("codify: attestations artefact is nil")
	}

	if outputDir == "" {
		outputDir = "tests/e2e/journeys"
	}

	// Build a lookup of passing attestations.
	passed := make(map[string]bool)
	for _, att := range attArtefact.Attestations {
		if att.Status == WalkPass {
			passed[att.JourneyID] = true
		}
	}

	var generated []string

	for i := range a.Journeys {
		j := &a.Journeys[i]

		if !passed[j.ID] {
			continue // not eligible — no passing walkthrough
		}

		// Already covered — accretive, skip.
		if j.HasRegression {
			continue
		}
		if j.RegressionTestPath != "" {
			if _, err := os.Stat(filepath.Join(projectRoot, j.RegressionTestPath)); err == nil {
				j.HasRegression = true
				continue
			}
		}

		// Codify this journey.
		relPath, err := CodifyJourney(j, outputDir, projectRoot)
		if err != nil {
			// If the file exists already, treat it as covered.
			if strings.Contains(err.Error(), "already exists") {
				j.HasRegression = true
				continue
			}
			return generated, fmt.Errorf("codify journey %s: %w", j.ID, err)
		}

		j.HasRegression = true
		j.RegressionTestPath = relPath
		generated = append(generated, relPath)
	}

	sort.Strings(generated)
	return generated, nil
}

// RegenScaffoldsPath returns the default output directory for regression
// scaffolds, relative to the project root.
const DefaultScaffoldsDir = "tests/e2e/journeys"
